---
# redis tasks/Debian.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Install Redis server
  apt:
    name:
      - "redis-server"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
  notify:
    - "start-redis"
