---
# redis handlers/main.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0


- name: start-redis
  service:
    name: "{{ redis_service }}"
    state: "started"
    enabled: true

- name: restart-redis
  service:
    name: "{{ redis_service }}"
    state: "restarted"
