---
# redis molecule/default/verify.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Converge
  hosts: all
  tasks:
    - name: "Include redis"
      include_role:
        name: "redis"
